# Generated by Django 5.1.2 on 2024-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_facebook_alter_blog_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=12)),
                ('Mensagem', models.TextField(max_length=1000)),
                ('lida', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='subnome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='capa',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
